### ISSUE TITLE
Info screen not sized correctly

### ISSUE THREAD

**Issue by TDWhbp** [trunzoc/WinkAtHome#16]
![winkathomefull](https://cloud.githubusercontent.com/assets/12042563/7270314/74bc2752-e8a9-11e4-8985-52ae18d784b0.PNG)
full screen
![winkathome](https://cloud.githubusercontent.com/assets/12042563/7270317/764f4658-e8a9-11e4-80c2-7549b1e793ae.PNG)
normal
attached is what i am seeing happening. unless i put browser in fullscreen i cannot see the close button on the info screens 

Tim

**Comment by TDWhbp** [comment]
latest update(pubHub) fixes this where do I look to fix it in the non pub hub ver?

**Comment by trunzoc** [comment]
There is no non-pubnub version.  I am adding the pubnub changes so that they should not affect a user that does not choose to use pubnub.  If the "pubnub" version is giving any type of error when you don't use the pubnub features, please do let me know.

**Comment by TDWhbp** [comment]
I noticed that I had to hard edit the user-name and password in the pubhub beta. it didn't allow me to just add them like prior versions

**Comment by trunzoc** [comment]
What do you mean hard-edit?  They should just be set through the settings page.

If the page isn't working, go back and make sure that the WinkAtHome folder and all files have IIS_IUSRS set to full control.  Especially check the WinkAtHome.SQLite file

**Comment by TDWhbp** [comment]
![no pubhub](https://cloud.githubusercontent.com/assets/12042563/7387868/d39a75c8-ee2e-11e4-9ee8-fd717e3bbd04.PNG)
if i fill out the settings with my correct username /password this is what I get Pubhub info or not. everything works if I manually edit settings and add my username and password. tried 3 times with a fresh install

**Comment by EricMCSE76** [comment]
TDW - I had this issue the other day because of doing the fresh install.  Going forward - if you don't delete the .SQLite file you won't run into this....that is what stores the info.    Craig had me close browser / re-open and go to http://localhost/WinkAtHome/default.aspx (rather than just localhost/WinkAtHome) which then redirected me back to the settings page and allowed me to put in username and password and save without issue.  Just don't delete the SQLite file next time if you do  "fresh" install.

**Comment by TDWhbp** [comment]
Ok case closed
